### PR TITLE
Update fastify jwt

### PR DESCRIPTION
**Pull request by vcanales**
Also add and update tests, and fix example.

### CODE REVIEW

**Comment by Ethan-Arrowood** [comment]
The commit history here is quite messy. If your only two changes are commits `63d926d` and `28b4193`. I recommend reset this branch to the head of my `add-fastify` branch and then cherry-picking those two commits.

**Comment by vcanales** [comment]
Done :)

**Comment by Ethan-Arrowood** [comment]
On your local machine check the output of `git log`. You can also see the history was not amended because the old commits are still display in this PR. 
My branch `ethan-arrowood:add-fastify` is currently on `688a502`
So you need to reset to that point, and then cherry pick 63d926d and 28b4193 on to there. `git reset` might not be the right command for this but it would be something like that.

**Comment by vcanales** [comment]
I'm pretty sure you're seeing the old commits because I force pushed after rebasing. This is my `git log`, which seems correct:

```terminal
$ git log --pretty=oneline --abbrev-commit
7775e7c (HEAD -> update-fastify-jwt, vcanales/update-fastify-jwt) update fastify integration demo
62de1b7 update fastify integration to use newer fastifyjwt
688a502 (earrowood/add-fastify) Add fastify v1 integration
dba6315 (tag: 1.2.1, earrowood/master) Release 1.2.1
4899dbf fixed index.d.ts for exposing functions (#25)
```

**Comment by Ethan-Arrowood** [comment]
You're right! Forgot to hard refresh browser. I'll merge this now :)

**Pull request merged**
